// This file provides a re-export of Obsidian module types
// Note: Shared test-utils are currently disabled
// Each plugin should define its own mocks as needed

// Export mock Obsidian classes and types
export {
  App,
  Plugin,
  PluginManifest,
  PluginSettingTab,
  Setting,
  Notice,
  TFile,
  TFolder,
  TAbstractFile,
  Vault,
  Workspace,
  WorkspaceLeaf,
  View,
  MarkdownView,
  Editor,
  EditorPosition,
  EditorRange,
  EditorSelection,
  EditorTransaction,
  MetadataCache,
  FileManager,
  FileStats,
  DataAdapter,
  Modal,
  SuggestModal,
  FuzzySuggestModal,
  Component,
  MarkdownRenderer,
  MarkdownPreviewRenderer,
  HoverParent,
  HoverPopover,
  Menu,
  MenuItem,
  Scope,
  ButtonComponent,
  TextComponent,
  TextAreaComponent,
  ToggleComponent,
  SliderComponent,
  DropdownComponent,
  ColorComponent,
  ExtraButtonComponent,
  normalizePath,
  moment,
} from 'obsidian';
