// This file provides a complete mock of the Obsidian module
// It re-exports all test utilities from shared package

export * from '@sb-obsidian-plugins/shared/src/test-utils';

// Export mock Obsidian classes and types
export {
  App,
  Plugin,
  PluginManifest,
  PluginSettingTab,
  Setting,
  Notice,
  TFile,
  TFolder,
  TAbstractFile,
  Vault,
  Workspace,
  WorkspaceLeaf,
  View,
  MarkdownView,
  Editor,
  EditorPosition,
  EditorRange,
  EditorSelection,
  EditorTransaction,
  MetadataCache,
  FileManager,
  FileStats,
  DataAdapter,
  Modal,
  SuggestModal,
  FuzzySuggestModal,
  Component,
  MarkdownRenderer,
  MarkdownPreviewRenderer,
  HoverParent,
  HoverPopover,
  Menu,
  MenuItem,
  Scope,
  ButtonComponent,
  TextComponent,
  TextAreaComponent,
  ToggleComponent,
  SliderComponent,
  DropdownComponent,
  ColorComponent,
  ExtraButtonComponent,
  normalizePath,
  moment,
} from 'obsidian';

// Re-export test utilities
export {
  createMockApp,
  createMockAppWithFiles,
  createMockVault,
  createMockWorkspace,
  createMockWorkspaceLeaf,
  createMockMarkdownView,
  createMockEditor,
  createMockPlugin,
  createMockPluginWithSettings,
  createMockPluginClass,
  createMockFile,
  createMockFolder,
  createFrontmatter,
  createMarkdownFile,
  extractFrontmatter,
  mockNotice,
  waitFor,
  waitForCall,
  withCleanup,
  expectToReject,
  createMockCommand,
  testData,
} from '@sb-obsidian-plugins/shared/src/test-utils';
